// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Helpers;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220903134842_ImplementingIAuditable")]
    partial class ImplementingIAuditable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Label = "China",
                            Value = "CN"
                        },
                        new
                        {
                            Id = 2L,
                            Label = "China, Hong Kong",
                            Value = "HK"
                        },
                        new
                        {
                            Id = 3L,
                            Label = "Singapore",
                            Value = "SG"
                        },
                        new
                        {
                            Id = 4L,
                            Label = "United States",
                            Value = "US"
                        },
                        new
                        {
                            Id = 5L,
                            Label = "Canada",
                            Value = "CA"
                        },
                        new
                        {
                            Id = 6L,
                            Label = "Afghanistan",
                            Value = "AF"
                        },
                        new
                        {
                            Id = 7L,
                            Label = "Åland Islands",
                            Value = "AX"
                        },
                        new
                        {
                            Id = 8L,
                            Label = "Albania",
                            Value = "AL"
                        },
                        new
                        {
                            Id = 9L,
                            Label = "Algeria",
                            Value = "DZ"
                        },
                        new
                        {
                            Id = 10L,
                            Label = "American Samoa",
                            Value = "AS"
                        },
                        new
                        {
                            Id = 11L,
                            Label = "Andorra",
                            Value = "AD"
                        },
                        new
                        {
                            Id = 12L,
                            Label = "Angola",
                            Value = "AO"
                        },
                        new
                        {
                            Id = 13L,
                            Label = "Anguilla",
                            Value = "AI"
                        },
                        new
                        {
                            Id = 14L,
                            Label = "Antarctica",
                            Value = "AQ"
                        },
                        new
                        {
                            Id = 15L,
                            Label = "Antigua and Barbuda",
                            Value = "AG"
                        },
                        new
                        {
                            Id = 16L,
                            Label = "Argentina",
                            Value = "AR"
                        },
                        new
                        {
                            Id = 17L,
                            Label = "Armenia",
                            Value = "AM"
                        },
                        new
                        {
                            Id = 18L,
                            Label = "Aruba",
                            Value = "AW"
                        },
                        new
                        {
                            Id = 19L,
                            Label = "Australia",
                            Value = "AU"
                        },
                        new
                        {
                            Id = 20L,
                            Label = "Austria",
                            Value = "AT"
                        },
                        new
                        {
                            Id = 21L,
                            Label = "Azerbaijan",
                            Value = "AZ"
                        },
                        new
                        {
                            Id = 22L,
                            Label = "Bahamas",
                            Value = "BS"
                        },
                        new
                        {
                            Id = 23L,
                            Label = "Bahrain",
                            Value = "BH"
                        },
                        new
                        {
                            Id = 24L,
                            Label = "Bangladesh",
                            Value = "BD"
                        },
                        new
                        {
                            Id = 25L,
                            Label = "Barbados",
                            Value = "BB"
                        },
                        new
                        {
                            Id = 26L,
                            Label = "Belarus",
                            Value = "BY"
                        },
                        new
                        {
                            Id = 27L,
                            Label = "Belgium",
                            Value = "BE"
                        },
                        new
                        {
                            Id = 28L,
                            Label = "Belize",
                            Value = "BZ"
                        },
                        new
                        {
                            Id = 29L,
                            Label = "Benin",
                            Value = "BJ"
                        },
                        new
                        {
                            Id = 30L,
                            Label = "Bermuda",
                            Value = "BM"
                        },
                        new
                        {
                            Id = 31L,
                            Label = "Bhutan",
                            Value = "BT"
                        },
                        new
                        {
                            Id = 32L,
                            Label = "Bolivia, Plurinational State of",
                            Value = "BO"
                        },
                        new
                        {
                            Id = 33L,
                            Label = "Bonaire, Sint Eustatius and Saba",
                            Value = "BQ"
                        },
                        new
                        {
                            Id = 34L,
                            Label = "Bosnia and Herzegovina",
                            Value = "BA"
                        },
                        new
                        {
                            Id = 35L,
                            Label = "Botswana",
                            Value = "BW"
                        },
                        new
                        {
                            Id = 36L,
                            Label = "Bouvet Island",
                            Value = "BV"
                        },
                        new
                        {
                            Id = 37L,
                            Label = "Brazil",
                            Value = "BR"
                        },
                        new
                        {
                            Id = 38L,
                            Label = "British Indian Ocean Territory",
                            Value = "IO"
                        },
                        new
                        {
                            Id = 39L,
                            Label = "Brunei Darussalam",
                            Value = "BN"
                        },
                        new
                        {
                            Id = 40L,
                            Label = "Bulgaria",
                            Value = "BG"
                        },
                        new
                        {
                            Id = 41L,
                            Label = "Burkina Faso",
                            Value = "BF"
                        },
                        new
                        {
                            Id = 42L,
                            Label = "Burundi",
                            Value = "BI"
                        },
                        new
                        {
                            Id = 43L,
                            Label = "Cambodia",
                            Value = "KH"
                        },
                        new
                        {
                            Id = 44L,
                            Label = "Cameroon",
                            Value = "CM"
                        },
                        new
                        {
                            Id = 45L,
                            Label = "Cape Verde",
                            Value = "CV"
                        },
                        new
                        {
                            Id = 46L,
                            Label = "Cayman Islands",
                            Value = "KY"
                        },
                        new
                        {
                            Id = 47L,
                            Label = "Central African Republic",
                            Value = "CF"
                        },
                        new
                        {
                            Id = 48L,
                            Label = "Chad",
                            Value = "TD"
                        },
                        new
                        {
                            Id = 49L,
                            Label = "Chile",
                            Value = "CL"
                        },
                        new
                        {
                            Id = 50L,
                            Label = "Christmas Island",
                            Value = "CX"
                        },
                        new
                        {
                            Id = 51L,
                            Label = "Cocos (Keeling) Islands",
                            Value = "CC"
                        },
                        new
                        {
                            Id = 52L,
                            Label = "Colombia",
                            Value = "CO"
                        },
                        new
                        {
                            Id = 53L,
                            Label = "Comoros",
                            Value = "KM"
                        },
                        new
                        {
                            Id = 54L,
                            Label = "Congo",
                            Value = "CG"
                        },
                        new
                        {
                            Id = 55L,
                            Label = "Congo, the Democratic Republic of the",
                            Value = "CD"
                        },
                        new
                        {
                            Id = 56L,
                            Label = "Cook Islands",
                            Value = "CK"
                        },
                        new
                        {
                            Id = 57L,
                            Label = "Costa Rica",
                            Value = "CR"
                        },
                        new
                        {
                            Id = 58L,
                            Label = "Côte d'Ivoire",
                            Value = "CI"
                        },
                        new
                        {
                            Id = 59L,
                            Label = "Croatia",
                            Value = "HR"
                        },
                        new
                        {
                            Id = 60L,
                            Label = "Cuba",
                            Value = "CU"
                        },
                        new
                        {
                            Id = 61L,
                            Label = "Curaçao",
                            Value = "CW"
                        },
                        new
                        {
                            Id = 62L,
                            Label = "Cyprus",
                            Value = "CY"
                        },
                        new
                        {
                            Id = 63L,
                            Label = "Czech Republic",
                            Value = "CZ"
                        },
                        new
                        {
                            Id = 64L,
                            Label = "Denmark",
                            Value = "DK"
                        },
                        new
                        {
                            Id = 65L,
                            Label = "Djibouti",
                            Value = "DJ"
                        },
                        new
                        {
                            Id = 66L,
                            Label = "Dominica",
                            Value = "DM"
                        },
                        new
                        {
                            Id = 67L,
                            Label = "Dominican Republic",
                            Value = "DO"
                        },
                        new
                        {
                            Id = 68L,
                            Label = "Ecuador",
                            Value = "EC"
                        },
                        new
                        {
                            Id = 69L,
                            Label = "Egypt",
                            Value = "EG"
                        },
                        new
                        {
                            Id = 70L,
                            Label = "El Salvador",
                            Value = "SV"
                        },
                        new
                        {
                            Id = 71L,
                            Label = "Equatorial Guinea",
                            Value = "GQ"
                        },
                        new
                        {
                            Id = 72L,
                            Label = "Eritrea",
                            Value = "ER"
                        },
                        new
                        {
                            Id = 73L,
                            Label = "Estonia",
                            Value = "EE"
                        },
                        new
                        {
                            Id = 74L,
                            Label = "Ethiopia",
                            Value = "ET"
                        },
                        new
                        {
                            Id = 75L,
                            Label = "Falkland Islands (Malvinas)",
                            Value = "FK"
                        },
                        new
                        {
                            Id = 76L,
                            Label = "Faroe Islands",
                            Value = "FO"
                        },
                        new
                        {
                            Id = 77L,
                            Label = "Fiji",
                            Value = "FJ"
                        },
                        new
                        {
                            Id = 78L,
                            Label = "Finland",
                            Value = "FI"
                        },
                        new
                        {
                            Id = 79L,
                            Label = "France",
                            Value = "FR"
                        },
                        new
                        {
                            Id = 80L,
                            Label = "French Guiana",
                            Value = "GF"
                        },
                        new
                        {
                            Id = 81L,
                            Label = "French Polynesia",
                            Value = "PF"
                        },
                        new
                        {
                            Id = 82L,
                            Label = "French Southern Territories",
                            Value = "TF"
                        },
                        new
                        {
                            Id = 83L,
                            Label = "Gabon",
                            Value = "GA"
                        },
                        new
                        {
                            Id = 84L,
                            Label = "Gambia",
                            Value = "GM"
                        },
                        new
                        {
                            Id = 85L,
                            Label = "Georgia",
                            Value = "GE"
                        },
                        new
                        {
                            Id = 86L,
                            Label = "Germany",
                            Value = "DE"
                        },
                        new
                        {
                            Id = 87L,
                            Label = "Ghana",
                            Value = "GH"
                        },
                        new
                        {
                            Id = 88L,
                            Label = "Gibraltar",
                            Value = "GI"
                        },
                        new
                        {
                            Id = 89L,
                            Label = "Greece",
                            Value = "GR"
                        },
                        new
                        {
                            Id = 90L,
                            Label = "Greenland",
                            Value = "GL"
                        },
                        new
                        {
                            Id = 91L,
                            Label = "Grenada",
                            Value = "GD"
                        },
                        new
                        {
                            Id = 92L,
                            Label = "Guadeloupe",
                            Value = "GP"
                        },
                        new
                        {
                            Id = 93L,
                            Label = "Guam",
                            Value = "GU"
                        },
                        new
                        {
                            Id = 94L,
                            Label = "Guatemala",
                            Value = "GT"
                        },
                        new
                        {
                            Id = 95L,
                            Label = "Guernsey",
                            Value = "GG"
                        },
                        new
                        {
                            Id = 96L,
                            Label = "Guinea",
                            Value = "GN"
                        },
                        new
                        {
                            Id = 97L,
                            Label = "Guinea-Bissau",
                            Value = "GW"
                        },
                        new
                        {
                            Id = 98L,
                            Label = "Guyana",
                            Value = "GY"
                        },
                        new
                        {
                            Id = 99L,
                            Label = "Haiti",
                            Value = "HT"
                        },
                        new
                        {
                            Id = 100L,
                            Label = "Heard Island and McDonald Islands",
                            Value = "HM"
                        },
                        new
                        {
                            Id = 101L,
                            Label = "Holy See (Vatican City State)",
                            Value = "VA"
                        },
                        new
                        {
                            Id = 102L,
                            Label = "Honduras",
                            Value = "HN"
                        },
                        new
                        {
                            Id = 103L,
                            Label = "Hungary",
                            Value = "HU"
                        },
                        new
                        {
                            Id = 104L,
                            Label = "Iceland",
                            Value = "IS"
                        },
                        new
                        {
                            Id = 105L,
                            Label = "India",
                            Value = "IN"
                        },
                        new
                        {
                            Id = 106L,
                            Label = "Indonesia",
                            Value = "ID"
                        },
                        new
                        {
                            Id = 107L,
                            Label = "Iran, Islamic Republic of",
                            Value = "IR"
                        },
                        new
                        {
                            Id = 108L,
                            Label = "Iraq",
                            Value = "IQ"
                        },
                        new
                        {
                            Id = 109L,
                            Label = "Ireland",
                            Value = "IE"
                        },
                        new
                        {
                            Id = 110L,
                            Label = "Isle of Man",
                            Value = "IM"
                        },
                        new
                        {
                            Id = 111L,
                            Label = "Israel",
                            Value = "IL"
                        },
                        new
                        {
                            Id = 112L,
                            Label = "Italy",
                            Value = "IT"
                        },
                        new
                        {
                            Id = 113L,
                            Label = "Jamaica",
                            Value = "JM"
                        },
                        new
                        {
                            Id = 114L,
                            Label = "Japan",
                            Value = "JP"
                        },
                        new
                        {
                            Id = 115L,
                            Label = "Jersey",
                            Value = "JE"
                        },
                        new
                        {
                            Id = 116L,
                            Label = "Jordan",
                            Value = "JO"
                        },
                        new
                        {
                            Id = 117L,
                            Label = "Kazakhstan",
                            Value = "KZ"
                        },
                        new
                        {
                            Id = 118L,
                            Label = "Kenya",
                            Value = "KE"
                        },
                        new
                        {
                            Id = 119L,
                            Label = "Kiribati",
                            Value = "KI"
                        },
                        new
                        {
                            Id = 120L,
                            Label = "Korea, Democratic People's Republic of",
                            Value = "KP"
                        },
                        new
                        {
                            Id = 121L,
                            Label = "Korea, Republic of",
                            Value = "KR"
                        },
                        new
                        {
                            Id = 122L,
                            Label = "Kuwait",
                            Value = "KW"
                        },
                        new
                        {
                            Id = 123L,
                            Label = "Kyrgyzstan",
                            Value = "KG"
                        },
                        new
                        {
                            Id = 124L,
                            Label = "Lao People's Democratic Republic",
                            Value = "LA"
                        },
                        new
                        {
                            Id = 125L,
                            Label = "Latvia",
                            Value = "LV"
                        },
                        new
                        {
                            Id = 126L,
                            Label = "Lebanon",
                            Value = "LB"
                        },
                        new
                        {
                            Id = 127L,
                            Label = "Lesotho",
                            Value = "LS"
                        },
                        new
                        {
                            Id = 128L,
                            Label = "Liberia",
                            Value = "LR"
                        },
                        new
                        {
                            Id = 129L,
                            Label = "Libya",
                            Value = "LY"
                        },
                        new
                        {
                            Id = 130L,
                            Label = "Liechtenstein",
                            Value = "LI"
                        },
                        new
                        {
                            Id = 131L,
                            Label = "Lithuania",
                            Value = "LT"
                        },
                        new
                        {
                            Id = 132L,
                            Label = "Luxembourg",
                            Value = "LU"
                        },
                        new
                        {
                            Id = 133L,
                            Label = "Macao",
                            Value = "MO"
                        },
                        new
                        {
                            Id = 134L,
                            Label = "Macedonia, the Former Yugoslav Republic of",
                            Value = "MK"
                        },
                        new
                        {
                            Id = 135L,
                            Label = "Madagascar",
                            Value = "MG"
                        },
                        new
                        {
                            Id = 136L,
                            Label = "Malawi",
                            Value = "MW"
                        },
                        new
                        {
                            Id = 137L,
                            Label = "Malaysia",
                            Value = "MY"
                        },
                        new
                        {
                            Id = 138L,
                            Label = "Maldives",
                            Value = "MV"
                        },
                        new
                        {
                            Id = 139L,
                            Label = "Mali",
                            Value = "ML"
                        },
                        new
                        {
                            Id = 140L,
                            Label = "Malta",
                            Value = "MT"
                        },
                        new
                        {
                            Id = 141L,
                            Label = "Marshall Islands",
                            Value = "MH"
                        },
                        new
                        {
                            Id = 142L,
                            Label = "Martinique",
                            Value = "MQ"
                        },
                        new
                        {
                            Id = 143L,
                            Label = "Mauritania",
                            Value = "MR"
                        },
                        new
                        {
                            Id = 144L,
                            Label = "Mauritius",
                            Value = "MU"
                        },
                        new
                        {
                            Id = 145L,
                            Label = "Mayotte",
                            Value = "YT"
                        },
                        new
                        {
                            Id = 146L,
                            Label = "Mexico",
                            Value = "MX"
                        },
                        new
                        {
                            Id = 147L,
                            Label = "Micronesia, Federated States of",
                            Value = "FM"
                        },
                        new
                        {
                            Id = 148L,
                            Label = "Moldova, Republic of",
                            Value = "MD"
                        },
                        new
                        {
                            Id = 149L,
                            Label = "Monaco",
                            Value = "MC"
                        },
                        new
                        {
                            Id = 150L,
                            Label = "Mongolia",
                            Value = "MN"
                        },
                        new
                        {
                            Id = 151L,
                            Label = "Montenegro",
                            Value = "ME"
                        },
                        new
                        {
                            Id = 152L,
                            Label = "Montserrat",
                            Value = "MS"
                        },
                        new
                        {
                            Id = 153L,
                            Label = "Morocco",
                            Value = "MA"
                        },
                        new
                        {
                            Id = 154L,
                            Label = "Mozambique",
                            Value = "MZ"
                        },
                        new
                        {
                            Id = 155L,
                            Label = "Myanmar",
                            Value = "MM"
                        },
                        new
                        {
                            Id = 156L,
                            Label = "Namibia",
                            Value = "NA"
                        },
                        new
                        {
                            Id = 157L,
                            Label = "Nauru",
                            Value = "NR"
                        },
                        new
                        {
                            Id = 158L,
                            Label = "Nepal",
                            Value = "NP"
                        },
                        new
                        {
                            Id = 159L,
                            Label = "Netherlands",
                            Value = "NL"
                        },
                        new
                        {
                            Id = 160L,
                            Label = "New Caledonia",
                            Value = "NC"
                        },
                        new
                        {
                            Id = 161L,
                            Label = "New Zealand",
                            Value = "NZ"
                        },
                        new
                        {
                            Id = 162L,
                            Label = "Nicaragua",
                            Value = "NI"
                        },
                        new
                        {
                            Id = 163L,
                            Label = "Niger",
                            Value = "NE"
                        },
                        new
                        {
                            Id = 164L,
                            Label = "Nigeria",
                            Value = "NG"
                        },
                        new
                        {
                            Id = 165L,
                            Label = "Niue",
                            Value = "NU"
                        },
                        new
                        {
                            Id = 166L,
                            Label = "Norfolk Island",
                            Value = "NF"
                        },
                        new
                        {
                            Id = 167L,
                            Label = "Northern Mariana Islands",
                            Value = "MP"
                        },
                        new
                        {
                            Id = 168L,
                            Label = "Norway",
                            Value = "NO"
                        },
                        new
                        {
                            Id = 169L,
                            Label = "Oman",
                            Value = "OM"
                        },
                        new
                        {
                            Id = 170L,
                            Label = "Pakistan",
                            Value = "PK"
                        },
                        new
                        {
                            Id = 171L,
                            Label = "Palau",
                            Value = "PW"
                        },
                        new
                        {
                            Id = 172L,
                            Label = "Palestine, State of",
                            Value = "PS"
                        },
                        new
                        {
                            Id = 173L,
                            Label = "Panama",
                            Value = "PA"
                        },
                        new
                        {
                            Id = 174L,
                            Label = "Papua New Guinea",
                            Value = "PG"
                        },
                        new
                        {
                            Id = 175L,
                            Label = "Paraguay",
                            Value = "PY"
                        },
                        new
                        {
                            Id = 176L,
                            Label = "Peru",
                            Value = "PE"
                        },
                        new
                        {
                            Id = 177L,
                            Label = "Philippines",
                            Value = "PH"
                        },
                        new
                        {
                            Id = 178L,
                            Label = "Pitcairn",
                            Value = "PN"
                        },
                        new
                        {
                            Id = 179L,
                            Label = "Poland",
                            Value = "PL"
                        },
                        new
                        {
                            Id = 180L,
                            Label = "Portugal",
                            Value = "PT"
                        },
                        new
                        {
                            Id = 181L,
                            Label = "Puerto Rico",
                            Value = "PR"
                        },
                        new
                        {
                            Id = 182L,
                            Label = "Qatar",
                            Value = "QA"
                        },
                        new
                        {
                            Id = 183L,
                            Label = "Réunion",
                            Value = "RE"
                        },
                        new
                        {
                            Id = 184L,
                            Label = "Romania",
                            Value = "RO"
                        },
                        new
                        {
                            Id = 185L,
                            Label = "Russian Federation",
                            Value = "RU"
                        },
                        new
                        {
                            Id = 186L,
                            Label = "Rwanda",
                            Value = "RW"
                        },
                        new
                        {
                            Id = 187L,
                            Label = "Saint Barthélemy",
                            Value = "BL"
                        },
                        new
                        {
                            Id = 188L,
                            Label = "Saint Helena, Ascension and Tristan da Cunha",
                            Value = "SH"
                        },
                        new
                        {
                            Id = 189L,
                            Label = "Saint Kitts and Nevis",
                            Value = "KN"
                        },
                        new
                        {
                            Id = 190L,
                            Label = "Saint Lucia",
                            Value = "LC"
                        },
                        new
                        {
                            Id = 191L,
                            Label = "Saint Martin (French part)",
                            Value = "MF"
                        },
                        new
                        {
                            Id = 192L,
                            Label = "Saint Pierre and Miquelon",
                            Value = "PM"
                        },
                        new
                        {
                            Id = 193L,
                            Label = "Saint Vincent and the Grenadines",
                            Value = "VC"
                        },
                        new
                        {
                            Id = 194L,
                            Label = "Samoa",
                            Value = "WS"
                        },
                        new
                        {
                            Id = 195L,
                            Label = "San Marino",
                            Value = "SM"
                        },
                        new
                        {
                            Id = 196L,
                            Label = "Sao Tome and Principe",
                            Value = "ST"
                        },
                        new
                        {
                            Id = 197L,
                            Label = "Saudi Arabia",
                            Value = "SA"
                        },
                        new
                        {
                            Id = 198L,
                            Label = "Senegal",
                            Value = "SN"
                        },
                        new
                        {
                            Id = 199L,
                            Label = "Serbia",
                            Value = "RS"
                        },
                        new
                        {
                            Id = 200L,
                            Label = "Seychelles",
                            Value = "SC"
                        },
                        new
                        {
                            Id = 201L,
                            Label = "Sierra Leone",
                            Value = "SL"
                        },
                        new
                        {
                            Id = 202L,
                            Label = "Sint Maarten (Dutch part)",
                            Value = "SX"
                        },
                        new
                        {
                            Id = 203L,
                            Label = "Slovakia",
                            Value = "SK"
                        },
                        new
                        {
                            Id = 204L,
                            Label = "Slovenia",
                            Value = "SI"
                        },
                        new
                        {
                            Id = 205L,
                            Label = "Solomon Islands",
                            Value = "SB"
                        },
                        new
                        {
                            Id = 206L,
                            Label = "Somalia",
                            Value = "SO"
                        },
                        new
                        {
                            Id = 207L,
                            Label = "South Africa",
                            Value = "ZA"
                        },
                        new
                        {
                            Id = 208L,
                            Label = "South Georgia and the South Sandwich Islands",
                            Value = "GS"
                        },
                        new
                        {
                            Id = 209L,
                            Label = "South Sudan",
                            Value = "SS"
                        },
                        new
                        {
                            Id = 210L,
                            Label = "Spain",
                            Value = "ES"
                        },
                        new
                        {
                            Id = 211L,
                            Label = "Sri Lanka",
                            Value = "LK"
                        },
                        new
                        {
                            Id = 212L,
                            Label = "Sudan",
                            Value = "SD"
                        },
                        new
                        {
                            Id = 213L,
                            Label = "Suriname",
                            Value = "SR"
                        },
                        new
                        {
                            Id = 214L,
                            Label = "Svalbard and Jan Mayen",
                            Value = "SJ"
                        },
                        new
                        {
                            Id = 215L,
                            Label = "Swaziland",
                            Value = "SZ"
                        },
                        new
                        {
                            Id = 216L,
                            Label = "Sweden",
                            Value = "SE"
                        },
                        new
                        {
                            Id = 217L,
                            Label = "Switzerland",
                            Value = "CH"
                        },
                        new
                        {
                            Id = 218L,
                            Label = "Syrian Arab Republic",
                            Value = "SY"
                        },
                        new
                        {
                            Id = 219L,
                            Label = "Taiwan, Province of China",
                            Value = "TW"
                        },
                        new
                        {
                            Id = 220L,
                            Label = "Tajikistan",
                            Value = "TJ"
                        },
                        new
                        {
                            Id = 221L,
                            Label = "Tanzania, United Republic of",
                            Value = "TZ"
                        },
                        new
                        {
                            Id = 222L,
                            Label = "Thailand",
                            Value = "TH"
                        },
                        new
                        {
                            Id = 223L,
                            Label = "Timor-Leste",
                            Value = "TL"
                        },
                        new
                        {
                            Id = 224L,
                            Label = "Togo",
                            Value = "TG"
                        },
                        new
                        {
                            Id = 225L,
                            Label = "Tokelau",
                            Value = "TK"
                        },
                        new
                        {
                            Id = 226L,
                            Label = "Tonga",
                            Value = "TO"
                        },
                        new
                        {
                            Id = 227L,
                            Label = "Trinidad and Tobago",
                            Value = "TT"
                        },
                        new
                        {
                            Id = 228L,
                            Label = "Tunisia",
                            Value = "TN"
                        },
                        new
                        {
                            Id = 229L,
                            Label = "Turkey",
                            Value = "TR"
                        },
                        new
                        {
                            Id = 230L,
                            Label = "Turkmenistan",
                            Value = "TM"
                        },
                        new
                        {
                            Id = 231L,
                            Label = "Turks and Caicos Islands",
                            Value = "TC"
                        },
                        new
                        {
                            Id = 232L,
                            Label = "Tuvalu",
                            Value = "TV"
                        },
                        new
                        {
                            Id = 233L,
                            Label = "Uganda",
                            Value = "UG"
                        },
                        new
                        {
                            Id = 234L,
                            Label = "Ukraine",
                            Value = "UA"
                        },
                        new
                        {
                            Id = 235L,
                            Label = "United Arab Emirates",
                            Value = "AE"
                        },
                        new
                        {
                            Id = 236L,
                            Label = "United Kingdom",
                            Value = "GB"
                        },
                        new
                        {
                            Id = 237L,
                            Label = "United States Minor Outlying Islands",
                            Value = "UM"
                        },
                        new
                        {
                            Id = 238L,
                            Label = "Uruguay",
                            Value = "UY"
                        },
                        new
                        {
                            Id = 239L,
                            Label = "Uzbekistan",
                            Value = "UZ"
                        },
                        new
                        {
                            Id = 240L,
                            Label = "Vanuatu",
                            Value = "VU"
                        },
                        new
                        {
                            Id = 241L,
                            Label = "Venezuela, Bolivarian Republic of",
                            Value = "VE"
                        },
                        new
                        {
                            Id = 242L,
                            Label = "Viet Nam",
                            Value = "VN"
                        },
                        new
                        {
                            Id = 243L,
                            Label = "Virgin Islands, British",
                            Value = "VG"
                        },
                        new
                        {
                            Id = 244L,
                            Label = "Virgin Islands, U.S.",
                            Value = "VI"
                        },
                        new
                        {
                            Id = 245L,
                            Label = "Wallis and Futuna",
                            Value = "WF"
                        },
                        new
                        {
                            Id = 246L,
                            Label = "Western Sahara",
                            Value = "EH"
                        },
                        new
                        {
                            Id = 247L,
                            Label = "Yemen",
                            Value = "YE"
                        },
                        new
                        {
                            Id = 248L,
                            Label = "Zambia",
                            Value = "ZM"
                        },
                        new
                        {
                            Id = 249L,
                            Label = "Zimbabwe",
                            Value = "ZW"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BodyPart")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercise", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.Set", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AchievedCount")
                        .HasColumnType("bigint");

                    b.Property<long>("AchievedWeight")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TargetCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetWeight")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Set", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Age")
                        .HasColumnType("bigint");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("GivenName")
                        .HasColumnType("text");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Entities.Workout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("WorkoutType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Workout", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.WorkoutExerciseMapping", b =>
                {
                    b.Property<long>("WorkoutId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkoutId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("WorkoutExerciseMapping", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.WorkoutProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkoutProgram", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.WorkoutProgramMapping", b =>
                {
                    b.Property<long>("WorkoutProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkoutId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkoutProgramId", "WorkoutId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutProgramMapping", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.WorkoutProgramUserMapping", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkoutProgramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "WorkoutProgramId");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("WorkoutProgramUserMapping", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.Set", b =>
                {
                    b.HasOne("WebApi.Entities.Exercise", "Exercise")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("WebApi.Entities.User", b =>
                {
                    b.HasOne("WebApi.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebApi.Entities.WorkoutExerciseMapping", b =>
                {
                    b.HasOne("WebApi.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WebApi.Entities.WorkoutProgramMapping", b =>
                {
                    b.HasOne("WebApi.Entities.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.WorkoutProgram", "WorkoutProgram")
                        .WithMany()
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("WebApi.Entities.WorkoutProgramUserMapping", b =>
                {
                    b.HasOne("WebApi.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.WorkoutProgram", "WorkoutProgram")
                        .WithMany()
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("WebApi.Entities.Exercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
